
---
- name: Install NGINX From Apt-Get
  become: yes
  apt:
    name: nginx
    state: present

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd:  systemctl stop nginx.service

- name: Copy NGINX DVH
  become: yes
  command:
    cmd: rm -rf /etc/nginx/sites-available/default 

- name: Copy NGINX DVH
  become: yes
  command:
    cmd: rm -rf /etc/nginx/sites-enabled/default
 
- name: Create NGINX Conf File
  become: yes
  file:
    path: /etc/nginx/sites-available/default
    state: touch

- name: Amend NGINX Conf File
  become: yes
  blockinfile:
      path: /etc/nginx/sites-available/default
      marker: ""
      block: |
         server {
             listen 80;

                 server_name localhost;
                 location ~ /(.*) {
                             proxy_pass http://127.0.0.1:8000;
                             proxy_set_header X-Real-IP $remote_addr;
                             proxy_set_header Host $host;
                             proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                 }

             }

- name: Link NGINX  Reverse Proxy
  become: yes
  command:
    cmd: ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

- name: Make Sure NGINX Service Is Running
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Curl
  become: yes
  apt:
    name: curl
    state: present

- name: Download file from a file path
  become: yes
  command:
    cmd: mkdir /install/

- name: Download file from a file path
  get_url:
    url:  https://raw.githubusercontent.com/Chirikru/testing/main/install.sh
    dest: /install/

- name: run
  become: yes
  command:
    cmd: chmod +x /install/install.sh

- name: run
  become: yes
  command:
    cmd: /install/install.sh

- name: Download django
  become: yes
  command:
    cmd: git clone https://github.com/reljicd/django-blog.git

- name: Deleted old settings
  become: yes
  command:
    cmd: rm -rf ~/django-blog/mysite/settings.py

- name: download new settings
  get_url:
    url:  https://raw.githubusercontent.com/Chirikru/testing/main/settings.py
    dest: ~/django-blog/mysite/

- name: copy django
  become: yes
  command:
    cmd: cp -r ~/django-blog/. ~/

- name: Deleted old run_docker
  become: yes
  command:
    cmd: rm -rf ~/scripts/run_docker.sh

- name: download new run_docker.sh
  get_url:
    url:  https://raw.githubusercontent.com/Chirikru/testing/main/run_docker.sh
    dest: ~/scripts/

- name: chmod django
  become: yes
  command:
    cmd: chmod +x ~/scripts/run_docker.sh

- name: run django_docker
  become: yes
  command:
    cmd: scripts/run_docker.sh
