---
- name: Install NGINX From Apt-Get
  become: yes
  apt:
    name: nginx
    state: present

- name: Disable NGINX Default Virtual Host
  become: yes
  command:
    cmd:  systemctl stop nginx.service

- name: Copy NGINX DVH
  become: yes
  command:
    cmd: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.save
 
- name: Create NGINX Conf File
  become: yes
  file:
    path: /etc/nginx/sites-available/default
    state: touch

- name: Amend NGINX Conf File
  become: yes
  blockinfile:
      path: /etc/nginx/sites-available/default
      marker: ""
      block: |
         server {
             listen 80;
                 server_name localhost;
                 location ~ /(.*) {
                             proxy_pass http://127.0.0.1:8000;
                             proxy_set_header X-Real-IP $remote_addr;
                             proxy_set_header Host $host;
                             proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                 }
             }
- name: Link NGINX  Reverse Proxy
  become: yes
  command:
    cmd: ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

- name: Make Sure NGINX Service Is Running
  become: yes
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Curl
  become: yes
  command:
    cmd: apt install curl -y
         curl https://raw.githubusercontent.com/Chirikru/chik/master/install.sh -H 'Cache-Control: no-cache' | sudo sh
         
