route:
    group_by:
    - alertname
    group_wait: 10s
    group_interval: 1m 
    repeat_interval: 5m # каждые 5 минут пишет в телегу
    receiver: 'telegram'

receivers:
    - name: 'telegram'
      webhook_configs:
      - url: https://api.telegram.org/bot"АпиТелеграмма без кавычек"/sendmessage?chat_id="ID чата без кавычек"&text=%22AHTUNG%20Site%20DOWN%22 # he-he-he



