route:
    group_by:
    - alertname
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 30m
    receiver: 'pager'

receivers:
    - name: 'pager'
      webhook_configs:
      - url: https://api.telegram.org/bot5209561422:AAEEPNrU6AgO2IxBTykaehhonAQ4E6M37NY/sendmessage?chat_id=539686084&text=%22AHTUNG%20Site%20DOWN%22



